/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Run Stop Block",
  "description": "Adds a run (stop) block to the control category",
  "credits": [
    {
      "name": "PenguinMod"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [],
  "enabledByDefault": true
};
export default manifest;
