/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "If on Edge Block",
  "description": "Adds if on edge block as built-in to Motion category",
  "credits": [
    {
      "name": "PenguinMod"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [],
  "enabledByDefault": true
};
export default manifest;
